// Date: 08.07.2015 17:08:36
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.fravokados.peacehammer.client.model.tile;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelKingStone extends ModelBase {
	//fields
	ModelRenderer ThroneBase;
	ModelRenderer ThroneUpperBaseLeft;
	ModelRenderer ThroneStep;
	ModelRenderer ThroneUpperBaseRight;
	ModelRenderer TrhoneUpperBaseBack;
	ModelRenderer Back;
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Right;
	ModelRenderer Left;
	ModelRenderer Seat;

	public ModelKingStone() {
		textureWidth = 64;
		textureHeight = 32;

		ThroneBase = new ModelRenderer(this, 0, 10);
		ThroneBase.addBox(0F, 0F, 0F, 16, 2, 16);
		ThroneBase.setRotationPoint(-8F, 22F, -8F);
		ThroneBase.setTextureSize(64, 32);
		ThroneBase.mirror = true;
		setRotation(ThroneBase, 0F, 0F, 0F);
		ThroneUpperBaseLeft = new ModelRenderer(this, 0, 11);
		ThroneUpperBaseLeft.addBox(0F, 0F, 0F, 5, 5, 16);
		ThroneUpperBaseLeft.setRotationPoint(3F, 17F, -8F);
		ThroneUpperBaseLeft.setTextureSize(64, 32);
		ThroneUpperBaseLeft.mirror = true;
		setRotation(ThroneUpperBaseLeft, 0F, 0F, 0F);
		ThroneStep = new ModelRenderer(this, 0, 0);
		ThroneStep.addBox(0F, 0F, 0F, 6, 3, 4);
		ThroneStep.setRotationPoint(-3F, 19F, -5F);
		ThroneStep.setTextureSize(64, 32);
		ThroneStep.mirror = true;
		setRotation(ThroneStep, 0F, 0F, 0F);
		ThroneUpperBaseRight = new ModelRenderer(this, 0, 11);
		ThroneUpperBaseRight.addBox(0F, 0F, 0F, 5, 5, 16);
		ThroneUpperBaseRight.setRotationPoint(-8F, 17F, -8F);
		ThroneUpperBaseRight.setTextureSize(64, 32);
		ThroneUpperBaseRight.mirror = true;
		setRotation(ThroneUpperBaseRight, 0F, 0F, 0F);
		TrhoneUpperBaseBack = new ModelRenderer(this, 14, 14);
		TrhoneUpperBaseBack.addBox(0F, 0F, 0F, 6, 5, 9);
		TrhoneUpperBaseBack.setRotationPoint(-3F, 17F, -1F);
		TrhoneUpperBaseBack.setTextureSize(64, 32);
		TrhoneUpperBaseBack.mirror = true;
		setRotation(TrhoneUpperBaseBack, 0F, 0F, 0F);
		Back = new ModelRenderer(this, 44, 4);
		Back.addBox(0F, 0F, 0F, 8, 16, 2);
		Back.setRotationPoint(-4F, 1F, 5F);
		Back.setTextureSize(64, 32);
		Back.mirror = true;
		setRotation(Back, 0F, 0F, 0F);
		Shape1 = new ModelRenderer(this, 54, 7);
		Shape1.addBox(0F, 0F, 0F, 2, 7, 2);
		Shape1.setRotationPoint(-6F, 3F, 5F);
		Shape1.setTextureSize(64, 32);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 51, 7);
		Shape2.addBox(0F, 0F, 0F, 2, 7, 2);
		Shape2.setRotationPoint(4F, 3F, 5F);
		Shape2.setTextureSize(64, 32);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
		Right = new ModelRenderer(this, 0, 12);
		Right.addBox(0F, 0F, 0F, 3, 7, 8);
		Right.setRotationPoint(-7F, 10F, -1F);
		Right.setTextureSize(64, 32);
		Right.mirror = true;
		setRotation(Right, 0F, 0F, 0F);
		Left = new ModelRenderer(this, 0, 12);
		Left.addBox(0F, 0F, 0F, 3, 7, 8);
		Left.setRotationPoint(4F, 10F, -1F);
		Left.setTextureSize(64, 32);
		Left.mirror = true;
		setRotation(Left, 0F, 0F, 0F);
		Seat = new ModelRenderer(this, 38, 22);
		Seat.addBox(0F, 0F, 0F, 8, 5, 5);
		Seat.setRotationPoint(-4F, 12F, 0F);
		Seat.setTextureSize(64, 32);
		Seat.mirror = true;
		setRotation(Seat, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		ThroneBase.render(f5);
		ThroneUpperBaseLeft.render(f5);
		ThroneStep.render(f5);
		ThroneUpperBaseRight.render(f5);
		TrhoneUpperBaseBack.render(f5);
		Back.render(f5);
		Shape1.render(f5);
		Shape2.render(f5);
		Right.render(f5);
		Left.render(f5);
		Seat.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
