package com.fravokados.peacehammer.client.model.tile;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

@SideOnly(Side.CLIENT)
public class ModelGyroCopter extends ModelBase {
	//fields
	ModelRenderer blade1;
	ModelRenderer blade2;
	ModelRenderer blade3;
	ModelRenderer cone;
	ModelRenderer pipe1;
	ModelRenderer pipe0;
	ModelRenderer engineBase;
	ModelRenderer seat;
	ModelRenderer diagonal_strut;
	ModelRenderer plate_back;
	ModelRenderer cSurface_left;
	ModelRenderer cSurface_right;
	ModelRenderer cSurface_yaw;
	ModelRenderer bottom_shape;
	ModelRenderer strut1;
	ModelRenderer strut2;
	ModelRenderer skid1;
	ModelRenderer skid2;

	public ModelGyroCopter() {
		textureWidth = 256;
		textureHeight = 64;

		seat = new ModelRenderer(this, 0, 0);
		seat.addBox(0F, 0F, 0F, 16, 9, 17);
		seat.setRotationPoint(-8F, 11F, -8F);
		seat.setTextureSize(256, 64);
		seat.mirror = true;
		setRotation(seat, 0F, 0F, 0F);
		skid1 = new ModelRenderer(this, 0, 30);
		skid1.addBox(0F, 0F, 0F, 2, 2, 32);
		skid1.setRotationPoint(5F, 22F, -10F);
		skid1.setTextureSize(256, 64);
		skid1.mirror = true;
		setRotation(skid1, 0F, 0F, 0F);
		skid2 = new ModelRenderer(this, 0, 30);
		skid2.addBox(0F, 0F, 0F, 2, 2, 32);
		skid2.setRotationPoint(-7F, 22F, -10F);
		skid2.setTextureSize(256, 64);
		skid2.mirror = true;
		setRotation(skid2, 0F, 0F, 0F);
		engineBase = new ModelRenderer(this, 39, 45);
		engineBase.addBox(-1F, 0F, 0F, 8, 9, 6);
		engineBase.setRotationPoint(-3F, 10F, 9F);
		engineBase.setTextureSize(256, 64);
		engineBase.mirror = true;
		setRotation(engineBase, 0F, 0F, 0F);
		pipe1 = new ModelRenderer(this, 12, 53);
		pipe1.addBox(0F, 0F, 0F, 2, 7, 2);
		pipe1.setRotationPoint(-1F, -3F, 11F);
		pipe1.setTextureSize(256, 64);
		pipe1.mirror = true;
		setRotation(pipe1, 0F, 0F, 0F);
		pipe0 = new ModelRenderer(this, 12, 51);
		pipe0.addBox(0F, 0F, 0F, 4, 6, 4);
		pipe0.setRotationPoint(-2F, 4F, 10F);
		pipe0.setTextureSize(256, 64);
		pipe0.mirror = true;
		setRotation(pipe0, 0F, 0F, 0F);
		cone = new ModelRenderer(this, 12, 54);
		cone.addBox(0F, 0F, 0F, 4, 3, 4);
		cone.setRotationPoint(-2F, -6F, 10F);
		cone.setTextureSize(256, 64);
		cone.mirror = true;
		setRotation(cone, 0F, 0F, 0F);
		blade1 = new ModelRenderer(this, 85, 0);
		blade1.addBox(0F, 0F, 0F, 6, 1, 38);
		blade1.setRotationPoint(-3F, -5F, -28F);
		blade1.setTextureSize(256, 64);
		blade1.mirror = true;
		setRotation(blade1, 0F, 0F, 0F);
		blade2 = new ModelRenderer(this, 85, 0);
		blade2.addBox(0F, 0F, -1F, 6, 1, 38);
		blade2.setRotationPoint(1F, -5F, 17F);
		blade2.setTextureSize(256, 64);
		blade2.mirror = true;
		setRotation(blade2, 0F, 1.151917F, 0F);
		blade3 = new ModelRenderer(this, 85, 0);
		blade3.addBox(0F, 0F, 0F, 6, 1, 38);
		blade3.setRotationPoint(-3F, -5F, 11F);
		blade3.setTextureSize(256, 64);
		blade3.mirror = true;
		setRotation(blade3, 0F, -1.151917F, 0F);
		plate_back = new ModelRenderer(this, 69, 38);
		plate_back.addBox(0F, 0F, 0F, 6, 1, 25);
		plate_back.setRotationPoint(-3F, 16F, 15F);
		plate_back.setTextureSize(256, 64);
		plate_back.mirror = true;
		setRotation(plate_back, 0F, 0F, 0F);
		cSurface_left = new ModelRenderer(this, 80, 0);
		cSurface_left.addBox(0F, 0F, 0F, 6, 1, 14);
		cSurface_left.setRotationPoint(3F, 16F, 30F);
		cSurface_left.setTextureSize(256, 64);
		cSurface_left.mirror = true;
		setRotation(cSurface_left, 0F, 0F, 0F);
		cSurface_right = new ModelRenderer(this, 80, 0);
		cSurface_right.addBox(0F, 0F, 0F, 6, 1, 14);
		cSurface_right.setRotationPoint(-9F, 16F, 30F);
		cSurface_right.setTextureSize(256, 64);
		cSurface_right.mirror = true;
		setRotation(cSurface_right, 0F, 0F, 0F);
		diagonal_strut = new ModelRenderer(this, 68, 37);
		diagonal_strut.addBox(0F, 0F, 0F, 1, 1, 25);
		diagonal_strut.setRotationPoint(0F, 10F, 15F);
		diagonal_strut.setTextureSize(256, 64);
		diagonal_strut.mirror = true;
		setRotation(diagonal_strut, -0.2094395F, 0F, 0F);
		cSurface_yaw = new ModelRenderer(this, 170, 0);
		cSurface_yaw.addBox(0F, 0F, 0F, 1, 7, 14);
		cSurface_yaw.setRotationPoint(0F, 10F, 36.6F);
		cSurface_yaw.setTextureSize(256, 64);
		cSurface_yaw.mirror = true;
		setRotation(cSurface_yaw, 0F, 0F, 0F);
		strut1 = new ModelRenderer(this, 0, 49);
		strut1.addBox(0F, 0F, 0F, 2, 9, 2);
		strut1.setRotationPoint(5F, 13F, 9F);
		strut1.setTextureSize(256, 64);
		strut1.mirror = true;
		setRotation(strut1, 0F, 0F, 0F);
		strut2 = new ModelRenderer(this, 0, 49);
		strut2.addBox(0F, 0F, 0F, 2, 9, 2);
		strut2.setRotationPoint(-7F, 13F, 9F);
		strut2.setTextureSize(256, 64);
		strut2.mirror = true;
		setRotation(strut2, 0F, 0F, 0F);
		bottom_shape = new ModelRenderer(this, 145, 0);
		bottom_shape.addBox(0F, 0F, 0F, 4, 2, 8);
		bottom_shape.setRotationPoint(-2F, 20F, -5F);
		bottom_shape.setTextureSize(256, 64);
		bottom_shape.mirror = true;
		setRotation(bottom_shape, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		seat.render(f5);
		skid1.render(f5);
		skid2.render(f5);
		engineBase.render(f5);
		pipe1.render(f5);
		pipe0.render(f5);
		cone.render(f5);
		blade1.render(f5);
		blade2.render(f5);
		blade3.render(f5);
		plate_back.render(f5);
		cSurface_left.render(f5);
		cSurface_left.render(f5);
		diagonal_strut.render(f5);
		cSurface_yaw.render(f5);
		strut1.render(f5);
		strut2.render(f5);
		bottom_shape.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
